#ifndef BACKEND_NOTIFICATIONSERVICE_NETWORKMANAGER_NETWORKMANAGER_H_
#define BACKEND_NOTIFICATIONSERVICE_NETWORKMANAGER_NETWORKMANAGER_H_

#include "interfaces/IChatNetworkManager.h"

class NetworkManager : public IChatNetworkManager{

};


#endif  // BACKEND_NOTIFICATIONSERVICE_NETWORKMANAGER_NETWORKMANAGER_H_
